openapi: 3.0.3
info:
  title: nIT - OpenAPI 3.0
  description: >-
    This is nIT API documentation.
  version: '1.0.0'
servers:
  - url: /v1
tags:
  - name: auth
    description: Auth
  - name: register
    description: Register a new user
  - name: user
    description: Operations about user
  - name: events
    description: Operations about events
  - name: eventAdmin
    description: Manage drafts

paths:
  /auth/sendCode:
    post:
      tags:
        - auth
      summary: Send OTP code
      operationId: authSendCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCodeRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /auth/confirm:
    post:
      tags:
        - auth
      summary: Confirm OTP code
      operationId: authConfirmCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmOTPRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /auth/revoke:
    get:
      tags:
        - auth
      summary: Deactivate current session token and log out
      operationId: authRevokeSession
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'


  /register/sendCode:
    post:
      tags:
        - register
      summary: Send OTP code
      operationId: regSendCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SendCodeRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /register/confirm:
    post:
      tags:
        - register
      summary: Confirm OTP code
      operationId: regConfirmCode
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmOTPRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /register/finish:
    post:
      tags:
        - register
      summary: Complete registration process
      operationId: regFinish
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FinishRegistrationRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /getMe:
    get:
      tags:
        - user
      summary: Get current user profile
      description: Get current user profile
      operationId: getMe
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProfileResponse'
        '401':
          description: Unauthorized
        '400':
          description: Bad request

  /events/lookup:
    post:
      tags:
        - events
      summary: Search for events by filters
      operationId: eventsLookup
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EventsRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'

  /events/get/{uuid}:
    get:
      tags:
        - events
      summary: Get event by ID
      operationId: event
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventResponse'

  /events/fav:
    get:
      tags:
        - events
      summary: Get favorite events for current user
      operationId: get_fav_events
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'

  /events/fav/{uuid}/add:
    post:
      tags:
        - events
      summary: Add an event to favorites
      operationId: addToFav
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /events/fav/{uuid}/remove:
    post:
      tags:
        - events
      summary: Remove an event from favorites
      operationId: removeFromFav
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /eventAdmin/drafts:
    get:
      tags:
        - eventAdmin
      summary: Get all drafts
      operationId: drafts
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsResponse'

  /eventAdmin/create:
    post:
      tags:
        - eventAdmin
      summary: Create a new draft
      operationId: createDraft
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DraftCreationRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventHeaderResponse'

  /eventAdmin/setTags:
    post:
      tags:
        - eventAdmin
      summary: Set new tags for an event
      operationId: setTags
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetTagsRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /eventAdmin/setLinks:
    post:
      tags:
        - eventAdmin
      summary: Set new links for an event
      operationId: setLinks
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetLinksRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /eventAdmin/setSchedule:
    post:
      tags:
        - eventAdmin
      summary: Set new schedule for an event
      operationId: setSchedule
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SetScheduleRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

  /eventAdmin/edit:
    post:
      tags:
        - eventAdmin
      summary: Edit a draft
      operationId: editDraft
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EditDraftRequest'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventHeaderResponse'

  /eventAdmin/publish/{uuid}:
    post:
      tags:
        - eventAdmin
      summary: Publish a draft
      operationId: publishDraft
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ok'

components:
  schemas:
    EventResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        object:
          type: object
          properties:
            header:
              $ref: '#/components/schemas/EventHeaderResponse'
            links:
              type: array
              items:
                $ref: '#/components/schemas/EventLinkResponse'
            description:
              type: string
              example: 'Description of a test event11'

    EventsResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        object:
          type: array
          items:
            $ref: '#/components/schemas/EventHeaderResponse'
        status:
          type: integer
          format: int32
          example: 200

    EventHeaderResponse:
      type: object
      properties:
        uuid:
          type: string
          example: "b141fa84-8e25-11ee-8542-fa163e445fa2"
        title:
          type: string
          example: "Test paid event"
        priceLow:
          type: integer
          example: 100
        priceHigh:
          type: integer
          example: 500
        ageLimitLow:
          type: integer
          example: 12
        ageLimitHigh:
          type: integer
          example: 18
        location:
          type: string
          example: "56.822523, 60.605641 улица Декабристов, 77Б, Екатеринбург, Свердловская область, 620063"
        ownerInfo:
          type: string
          example: "ООО Тестовые Решения"
        hasCertificate:
          type: boolean
        favCount:
          type: integer
        createdAt:
          type: string
          format: date
        modifiedAt:
          type: string
          format: date
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/EventScheduleResponse'
        tags:
          type: array
          items:
            type: string
            example: [ "test", "хакатон", "командное", "соревнование" ]
        plainDescription:
          type: string
          example: "a paid event, come and have fun if you can afford it"
        isDraft:
          type: boolean
          example: false
        isMachineGenerated:
          type: boolean
          example: false

    EventLinkResponse:
      type: object
      properties:
        linkUUID:
          type: string
        title:
          type: string
          example: 'VK'
        url:
          type: string
          example: 'https://vk.com/durov'
        addedAt:
          type: string
          format: date

    EventScheduleResponse:
      type: object
      properties:
        scheduleUUID:
          type: string
        beginsAt:
          type: string
          format: date
        endsAt:
          type: string
          format: date
        addedAt:
          type: string
          format: date

    Ok:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        object:
          type: boolean
          format: boolean
        status:
          type: integer
          format: int32
          example: 200

    UserProfileResponse:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        object:
          type: object
          properties:
            uuid:
              type: string
              format: string
            phoneNumber:
              type: string
              format: string
            firstName:
              type: string
              format: string
            lastName:
              type: string
              format: string
            registeredAt:
              type: string
              format: date-time
            isAdmin:
              type: boolean
              format: boolean
        status:
          type: integer
          format: int32
          example: 200

    SendCodeRequest:
      type: object
      required:
        - phoneNumber
      properties:
        phoneNumber:
          type: string
          format: string
          example: '71112223344'

    ConfirmOTPRequest:
      type: object
      required:
        - code
      properties:
        code:
          type: string
          format: number
          example: '43251'

    FinishRegistrationRequest:
      type: object
      required:
        - firstName
      properties:
        firstName:
          type: string
          format: string
          example: 'Ivan'
        lastName:
          type: string
          format: string
          example: 'Petrov'

    EventsRequest:
      type: object
      required:
        - from
        - to
      properties:
        from:
          type: string
          format: date
          example: '2024-06-06T12:00:00+05:00'
        to:
          type: string
          format: date
          example: '2024-06-06T18:00:00+05:00'
        tags:
          type: array
          items:
            type: string
          example: ["test", "хакатон"]
        excludeAgeRestricted:
          type: boolean
          format: boolean
          example: false
        excludePaid:
          type: boolean
          format: boolean
          example: false

    DraftCreationRequest:
      type: object
      required:
        - title
        - priceLow
        - priceHigh
        - ageLimitLow
        - ageLimitHigh
        - location
        - ownerInfo
        - tags
        - plainDescription
      properties:
        title:
          type: string
          example: "First draft!"
        priceLow:
          type: integer
          example: 100
        priceHigh:
          type: integer
          example: 500
        ageLimitLow:
          type: integer
          example: 12
        ageLimitHigh:
          type: integer
          example: 18
        location:
          type: string
          example: "56.822523, 60.605641 улица Декабристов, 77Б, Екатеринбург, Свердловская область, 620063"
        ownerInfo:
          type: string
          example: "ООО Тестовые Решения"
        hasCertificate:
          type: boolean
        tags:
          type: array
          items:
            type: string
          example: [ "test", "хакатон", "командное", "соревнование" ]
        plainDescription:
          type: string
          example: "a paid event, come and have fun if you can afford it"
        isMachineGenerated:
          type: boolean
          example: false

    SetTagsRequest:
      type: object
      required:
        - eventUuid
        - tags
      properties:
        eventUuid:
          type: string
          example: 'f70dd14f-8e24-11ee-8542-fa163e445fa2'
        tags:
          type: array
          items:
            type: string
          example: [ "test", "хакатон", "командное", "соревнование" ]

    SetLinksRequest:
      type: object
      required:
        - eventUuid
        - links
      properties:
        eventUuid:
          type: string
          example: 'f70dd14f-8e24-11ee-8542-fa163e445fa2'
        links:
          type: array
          items:
            $ref: '#/components/schemas/SetLinkRequest'

    SetLinkRequest:
      type: object
      required:
        - title
        - url
      properties:
        title:
          type: string
          example: 'VK'
        url:
          type: string
          example: 'https://vk.com/durov'

    SetScheduleRequest:
      type: object
      required:
        - eventUuid
        - schedule
      properties:
        eventUuid:
          type: string
          example: 'f70dd14f-8e24-11ee-8542-fa163e445fa2'
        schedule:
          type: array
          items:
            $ref: '#/components/schemas/SetDayRequest'

    SetDayRequest:
      type: object
      required:
        - beginsAt
        - endsAt
      properties:
        beginsAt:
          type: string
          format: date
          example: '2024-06-06T12:00:00+05:00'
        endsAt:
          type: string
          format: date
          example: '2024-06-06T18:00:00+05:00'

    EditDraftRequest:
      type: object
      required:
        - eventUuid
        - object
      properties:
        eventUuid:
          type: string
          example: 'f70dd14f-8e24-11ee-8542-fa163e445fa2'
        object:
          $ref: '#/components/schemas/EditHeaderRequest'
        description:
          type: string
          example: 'Description of a test event11'

    EditHeaderRequest:
      type: object
      required:
        - title
        - priceLow
        - priceHigh
        - ageLimitLow
        - ageLimitHigh
        - location
        - ownerInfo
        - plainDescription
      properties:
        title:
          type: string
          example: "First draft!"
        priceLow:
          type: integer
          example: 100
        priceHigh:
          type: integer
          example: 500
        ageLimitLow:
          type: integer
          example: 12
        ageLimitHigh:
          type: integer
          example: 18
        location:
          type: string
          example: "56.822523, 60.605641 улица Декабристов, 77Б, Екатеринбург, Свердловская область, 620063"
        ownerInfo:
          type: string
          example: "ООО Тестовые Решения"
        hasCertificate:
          type: boolean
        plainDescription:
          type: string
          example: "a paid event, come and have fun if you can afford it"
        isMachineGenerated:
          type: boolean
          example: false
